[package]
name = "future"
version = "0.1.0"
authors = ["John KÃ¥re Alsaker <john.kare.alsaker@gmail.com>"]

[dependencies]
coroutine = { path = "../coroutine" }
future_traits = { path = "../future-traits" }